language: php
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - "/^v?[0-9\\.]+$/"
php:
- 5.6
- 7.1
env:
  matrix:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.7 WP_MULTISITE=0
  global:
  - SVN_REPO: https://plugins.svn.wordpress.org/wp-yomigana/
  - secure: "ow/7zbHLorjUZZh6hZbo61UCqk8Q49JZ5eWu+GMlHSa7qS1ECvhXKjqe9iw1t42W6g6p/JEMJhdPLbzxK1cGk7hUgQjFXaofY1ZRuxkFtRmF3dTYehqdhTIdUmkV/UDnL5dwAt6r4rSd/PrqcmArSn1CdY2D1znIwvMN5QGg9TI="
matrix:
  include:
  - php: 7.1
    env: WP_VERSION=latest WP_MULTISITE=0 WP_PULUGIN_DEPLOY=1
before_script:
- composer install
- curl -s -o $HOME/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.33.8/nvm.sh
- source $HOME/.nvm/nvm.sh
- nvm install v6.11.0
- node --version
- npm install && npm run package
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
- composer test
after_success: curl -L https://raw.githubusercontent.com/miya0001/travis2wpplugin/master/deploy.sh | bash
